/*
 * imx93-hello-ta -- the Secure-World half of this demo.
 *
 * Where this code actually runs:
 *   This .c file gets compiled and linked by OP-TEE's own TA build system
 *   (ta_dev_kit.mk, pulled in by ./Makefile) into a small standalone ELF,
 *   which then gets *signed* and repackaged into a ".ta" file. That .ta
 *   file is what ships in the rootfs, at /lib/optee_armtz/<this-TA's-UUID>.ta
 *   (see the recipe's do_install()).
 *
 *   At runtime, none of this code executes until a Normal-world client
 *   (host/main.c) calls TEEC_OpenSession() with this TA's UUID. That call
 *   goes: client (EL0) --ioctl(/dev/tee0)--> Linux TEE driver (EL1)
 *   --smc--> BL31 monitor (EL3, flips SCR.NS) --> OP-TEE core (S-EL1).
 *   OP-TEE core is the thing that actually finds this .ta file (via
 *   tee-supplicant, since it's a REE FS TA -- see the top-level README),
 *   verifies its signature, loads it into a fresh S-EL0 user-mode context,
 *   and only THEN starts calling the entry points below.
 *
 *   So every function in this file runs at S-EL0: same privilege level as
 *   a normal Linux userland process, but in the OTHER world -- it cannot
 *   see Normal-world (Linux) memory at all, and Linux/EL1/EL0 cannot see
 *   this TA's memory either, no matter how privileged (even root, even a
 *   compromised kernel). That mutual invisibility, enforced by hardware on
 *   every single memory access, IS TrustZone -- everything else in this
 *   BSP is just plumbing to get a request in here and a result back out.
 */

/*
 * tee_internal_api.h / tee_internal_api_extensions.h are part of the OP-TEE
 * "TA devkit" -- a set of headers + a tiny libutee/libutils staticlib meant
 * ONLY for code that runs at S-EL0. They are NOT the same headers a normal
 * Linux userland program would use (no libc, no syscalls as Linux knows
 * them) -- this is intentionally a much smaller, purpose-built API, exactly
 * because the whole point of a TEE is to have less code (and so fewer bugs)
 * behind the hardware wall. These headers physically don't exist on this
 * host machine -- they get generated by building optee-os and are staged
 * into the Yocto sysroot at:
 *   ${STAGING_INCDIR}/optee/export-user_ta_arm64/include/
 * which is exactly the TA_DEV_KIT_DIR this recipe's do_compile() points at.
 */
#include <tee_internal_api.h>
#include <tee_internal_api_extensions.h>

/* Shared with host/main.c -- the UUID and command-ID contract (see that
 * file's own comments for the full explanation). */
#include <imx93_hello_ta.h>

/*
 * TA_CreateEntryPoint() -- called ONCE, the very first time OP-TEE loads
 * this TA into memory (i.e. on the first session anyone opens against this
 * UUID after boot -- OP-TEE keeps a TA instance loaded and reuses it for
 * later sessions rather than reloading the .ta file every time). This is
 * the place for one-time setup: allocating a global secure-storage handle,
 * initializing a hardware crypto engine, etc. This demo needs none of that.
 *
 * Returning anything other than TEE_SUCCESS here aborts the load entirely
 * -- OP-TEE will refuse to run this TA and the client's TEEC_OpenSession()
 * will fail.
 */
TEE_Result TA_CreateEntryPoint(void)
{
	return TEE_SUCCESS;
}

/*
 * TA_DestroyEntryPoint() -- the mirror image of the above: called once,
 * when OP-TEE finally unloads this TA (e.g. under memory pressure, or on a
 * clean OP-TEE shutdown). Free anything TA_CreateEntryPoint() allocated.
 * No return value -- there is nothing left to fail back to at this point.
 */
void TA_DestroyEntryPoint(void)
{
}

/*
 * TA_OpenSessionEntryPoint() -- called every time a NEW client calls
 * TEEC_OpenSession() against this TA's UUID (unlike Create/Destroy above,
 * which are per-TA-instance, this one is per-CLIENT-connection -- OP-TEE
 * supports multiple simultaneous sessions from different Normal-world
 * processes against the same loaded TA).
 *
 * Arguments (all unused here, hence the __unused annotations -- a GCC/Clang
 * attribute meaning "yes, I know I'm not touching this parameter, don't
 * warn me"):
 *   param_types -- encodes the TYPE of each of the 4 params[] slots below
 *                  (value, memref, none, ...) -- see inc_value() further
 *                  down for a real example of decoding this.
 *   params[4]   -- up to 4 arguments the client passed to
 *                  TEEC_OpenSession()'s optional TEEC_Operation -- this
 *                  demo's client passes none at open time, only at invoke
 *                  time (see TA_InvokeCommandEntryPoint below).
 *   sess_ctx    -- an OUT parameter: whatever pointer you write here is
 *                  handed back to you, unmodified, as the sess_ctx argument
 *                  of every later TA_InvokeCommandEntryPoint()/
 *                  TA_CloseSessionEntryPoint() call for THIS session. Used
 *                  for per-session state (e.g. "which user opened this",
 *                  a session-local buffer). This demo is stateless, so it's
 *                  left untouched (NULL).
 *
 * IMSG() is OP-TEE's "info message" log macro -- prints from INSIDE Secure
 * World, at S-EL1's UART console (the "Secure World" console -- see the
 * repo's optee-trustzone-hands-on.md, section on CFG_TEE_CORE_LOG_LEVEL).
 * This board currently builds OP-TEE with CFG_TEE_TA_LOG_LEVEL=0 -- the
 * quietest setting -- so IMSG() calls in TAs are compiled out / silenced by
 * default on this exact image. See that doc for how to turn the log level
 * back up if you want to actually SEE this line print.
 */
TEE_Result TA_OpenSessionEntryPoint(uint32_t param_types __unused,
				     TEE_Param params[4] __unused,
				     void **sess_ctx __unused)
{
	IMSG("imx93-hello-ta: session opened");
	return TEE_SUCCESS;
}

/*
 * TA_CloseSessionEntryPoint() -- called when the client calls
 * TEEC_CloseSession() (or disconnects/crashes and OP-TEE cleans up after
 * it). sess_ctx here is exactly what TA_OpenSessionEntryPoint() wrote into
 * *sess_ctx above -- this demo never set it, so it's NULL. No return value:
 * a session close cannot be "refused".
 */
void TA_CloseSessionEntryPoint(void *sess_ctx __unused)
{
	IMSG("imx93-hello-ta: session closed");
}

/*
 * inc_value() -- the actual "business logic" of this TA. Not an entry
 * point itself (OP-TEE never calls this name directly) -- it's called from
 * TA_InvokeCommandEntryPoint() below when cmd_id says to. Split out into
 * its own function simply so the command dispatch (the switch statement
 * below) stays readable as you add more commands.
 *
 * param_types tells you, 2 bits per slot, what's actually sitting in each
 * of the 4 params[] entries this call was made with. TEE_PARAM_TYPES() is
 * a macro (from tee_internal_api.h) that packs 4 such 2-bit fields into one
 * uint32_t -- exactly mirroring how the CLIENT side packed them with
 * TEEC_PARAM_TYPES() in host/main.c. This TA is strict: it demands EXACTLY
 * one TEE_PARAM_TYPE_VALUE_INOUT (an in/out 32-bit integer pair, params[i]
 * .value.a / .value.b) in slot 0, and nothing (TEE_PARAM_TYPE_NONE) in the
 * other three. Any other combination is rejected outright.
 *
 * This check matters more than it looks: parameter types/counts are the
 * FIRST thing a TA must validate on every single invocation. The Normal
 * world is untrusted by definition (module 5's whole point) -- a
 * compromised or simply buggy CA could ask for a completely different
 * shape of call, and a TA that assumed the "expected" shape without
 * checking is exactly the class of S-EL0 bug the course's "Issues and
 * Limitations" section (real Qualcomm/Samsung CVEs) is about.
 */
static TEE_Result inc_value(uint32_t param_types, TEE_Param params[4])
{
	uint32_t exp_pt = TEE_PARAM_TYPES(TEE_PARAM_TYPE_VALUE_INOUT,
					   TEE_PARAM_TYPE_NONE,
					   TEE_PARAM_TYPE_NONE,
					   TEE_PARAM_TYPE_NONE);
	if (param_types != exp_pt)
		return TEE_ERROR_BAD_PARAMETERS;

	/* This line is the ENTIRE point of the demo: this addition happens
	 * inside Secure World. Nothing in Normal World -- not root, not a
	 * kernel exploit, not physical access to RAM from the Linux side --
	 * can observe or interrupt this instruction executing. Only the
	 * input (42, from the client) and the output (43, back to the
	 * client) ever cross the world boundary; the increment itself is
	 * S-EL0-only. Replace this one line with "sign this hash with a
	 * key that lives only in secure storage" and you have the shape of
	 * every real TA use case in the course's section 9 (software HSM,
	 * fTPM, DRM, biometrics, ...). */
	IMSG("imx93-hello-ta: incrementing %u inside the secure world",
	     params[0].value.a);
	params[0].value.a++;
	return TEE_SUCCESS;
}

/*
 * TA_InvokeCommandEntryPoint() -- called once per TEEC_InvokeCommand() the
 * client makes on an already-open session (a session can have many
 * invokes; open/close only happen once each). THIS is the function that
 * actually runs at the far end of the svc->smc->S-EL1-dispatch->S-EL0
 * chain described in the course's section 3.2 sequence diagram -- by the
 * time execution reaches here, the CPU has already: taken an `smc` in
 * Normal-world EL1, been caught by BL31 (the resident EL3 Secure Monitor
 * from this repo's own boot banners), had SCR.NS flipped to 0, been routed
 * into OP-TEE core at S-EL1, and been dispatched by OP-TEE core into THIS
 * TA's own S-EL0 context, matched to the session by sess_ctx.
 *
 * cmd_id is the plain integer the client passed as the second argument to
 * TEEC_InvokeCommand() -- this demo only understands
 * TA_IMX93_HELLO_CMD_INC_VALUE (== 0, from the shared header); everything
 * else is rejected. A real TA with multiple operations (e.g. the course's
 * capstone "keystore" TA: GENERATE_KEY / SIGN) would just add more `case`
 * arms here -- the dispatch pattern doesn't change, only the number of
 * commands and what each one is allowed to touch.
 */
TEE_Result TA_InvokeCommandEntryPoint(void *sess_ctx __unused, uint32_t cmd_id,
				       uint32_t param_types,
				       TEE_Param params[4])
{
	switch (cmd_id) {
	case TA_IMX93_HELLO_CMD_INC_VALUE:
		return inc_value(param_types, params);
	default:
		/* Unknown command ID -- reject rather than guess. A CA
		 * bug or a hostile CA probing for undocumented commands
		 * both get the same answer: no. */
		return TEE_ERROR_BAD_PARAMETERS;
	}
}
