# See imx93-hello-ta/files/ta/Makefile for a fully commented explanation
# of what this file does and why -- identical mechanism, just this TA's
# own UUID as BINARY.
BINARY = 88344489-54f5-429e-9a70-be08fe7c81cf

-include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk

clean:
	@$(RM) -f $(sub-dirs-out) $(cleanfiles)
